local _e0 = vgui.Create("DFrame")
_e0:SetWidth(700)
_e0:SetHeight(500)
local _e1 = vgui.Create("DButton", _e0)
_e1:SetWidth(_e0:GetTall() * 0.5)
_e1:SetText("Привет")
_e1.DoClick = (function() print("Привет!") end)
local _e2 = vgui.Create("DLabel", _e0)
_e2:SetSize(_e0:GetWidth() * 0.3, _e0:GetTall() * 0.5)
_e2:SetText("Простая текстовая метка")
